// Auto-generated by scripts/gen-supabase-types.sh
// npx supabase gen types typescript --project-id gedxzunoyzmvbqgwjalx --schema public
// Run `npm run gen-types` to regenerate after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      machines: {
        Row: {
          machine_code: string
          store_code: string
          machine_name: string | null
          machine_number: string | null
          type_id: number | null
          model_id: string | null
          play_price: number | null
          notes: string | null
          is_active: boolean
          meter_unit_price: number
          out_meter_count: number
          organization_id: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          machine_code: string
          store_code: string
          machine_name?: string | null
          machine_number?: string | null
          type_id?: number | null
          model_id?: string | null
          play_price?: number | null
          notes?: string | null
          is_active?: boolean
          meter_unit_price?: number
          out_meter_count?: number
          organization_id: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          machine_code?: string
          store_code?: string
          machine_name?: string | null
          machine_number?: string | null
          type_id?: number | null
          model_id?: string | null
          play_price?: number | null
          notes?: string | null
          is_active?: boolean
          meter_unit_price?: number
          out_meter_count?: number
          organization_id?: string
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'machines_store_code_fkey'
            columns: ['store_code']
            referencedRelation: 'stores'
            referencedColumns: ['store_code']
          },
        ]
      }
      meter_readings: {
        Row: {
          reading_id: string
          booth_id: string | null
          booth_code: string | null
          full_booth_code: string | null
          store_code: string | null
          machine_code: string | null
          patrol_date: string | null
          read_time: string | null
          in_meter: number | null
          out_meter: number | null
          out_meter_2: number | null
          out_meter_3: number | null
          in_diff: number | null
          out_diff_1: number | null
          out_diff_2: number | null
          out_diff_3: number | null
          prize_id: string | null
          prize_name: string | null
          prize_name_2: string | null
          prize_name_3: string | null
          prize_cost: number | null
          prize_cost_1: number | null
          prize_cost_2: number | null
          prize_cost_3: number | null
          prize_stock_count: number | null
          prize_restock_count: number | null
          stock_2: number | null
          stock_3: number | null
          restock_2: number | null
          restock_3: number | null
          theoretical_stock: number | null
          payout_rate: number | null
          set_a: string | null
          set_c: string | null
          set_l: string | null
          set_r: string | null
          set_o: string | null
          entry_type: 'patrol' | 'replace' | 'collection' | 'carry_forward' | null
          revenue: number | null
          play_price: number | null
          note: string | null
          source: string | null
          input_method: string | null
          staff_id: string | null
          ocr_confidence: number | null
          ocr_raw_text: string | null
          ocr_attempted_at: string | null
          photo_url: string | null
          cropped_photo_url: string | null
          organization_id: string
          created_at: string | null
          created_by: string | null
          updated_at: string | null
          updated_by: string | null
        }
        Insert: {
          reading_id?: string
          booth_id?: string | null
          booth_code?: string | null
          full_booth_code?: string | null
          store_code?: string | null
          machine_code?: string | null
          patrol_date?: string | null
          read_time?: string | null
          in_meter?: number | null
          out_meter?: number | null
          out_meter_2?: number | null
          out_meter_3?: number | null
          in_diff?: number | null
          out_diff_1?: number | null
          out_diff_2?: number | null
          out_diff_3?: number | null
          prize_id?: string | null
          prize_name?: string | null
          prize_name_2?: string | null
          prize_name_3?: string | null
          prize_cost?: number | null
          prize_cost_1?: number | null
          prize_cost_2?: number | null
          prize_cost_3?: number | null
          prize_stock_count?: number | null
          prize_restock_count?: number | null
          stock_2?: number | null
          stock_3?: number | null
          restock_2?: number | null
          restock_3?: number | null
          theoretical_stock?: number | null
          payout_rate?: number | null
          set_a?: string | null
          set_c?: string | null
          set_l?: string | null
          set_r?: string | null
          set_o?: string | null
          entry_type?: 'patrol' | 'replace' | 'collection' | 'carry_forward' | null
          revenue?: number | null
          play_price?: number | null
          note?: string | null
          source?: string | null
          input_method?: string | null
          staff_id?: string | null
          ocr_confidence?: number | null
          ocr_raw_text?: string | null
          ocr_attempted_at?: string | null
          photo_url?: string | null
          cropped_photo_url?: string | null
          organization_id: string
          created_at?: string | null
          created_by?: string | null
          updated_at?: string | null
          updated_by?: string | null
        }
        Update: {
          reading_id?: string
          booth_id?: string | null
          booth_code?: string | null
          full_booth_code?: string | null
          store_code?: string | null
          machine_code?: string | null
          patrol_date?: string | null
          read_time?: string | null
          in_meter?: number | null
          out_meter?: number | null
          out_meter_2?: number | null
          out_meter_3?: number | null
          in_diff?: number | null
          out_diff_1?: number | null
          out_diff_2?: number | null
          out_diff_3?: number | null
          prize_id?: string | null
          prize_name?: string | null
          prize_name_2?: string | null
          prize_name_3?: string | null
          prize_cost?: number | null
          prize_cost_1?: number | null
          prize_cost_2?: number | null
          prize_cost_3?: number | null
          prize_stock_count?: number | null
          prize_restock_count?: number | null
          stock_2?: number | null
          stock_3?: number | null
          restock_2?: number | null
          restock_3?: number | null
          theoretical_stock?: number | null
          payout_rate?: number | null
          set_a?: string | null
          set_c?: string | null
          set_l?: string | null
          set_r?: string | null
          set_o?: string | null
          entry_type?: 'patrol' | 'replace' | 'collection' | 'carry_forward' | null
          revenue?: number | null
          play_price?: number | null
          note?: string | null
          source?: string | null
          input_method?: string | null
          staff_id?: string | null
          ocr_confidence?: number | null
          ocr_raw_text?: string | null
          ocr_attempted_at?: string | null
          photo_url?: string | null
          cropped_photo_url?: string | null
          organization_id?: string
          created_at?: string | null
          created_by?: string | null
          updated_at?: string | null
          updated_by?: string | null
        }
        Relationships: []
      }
      prize_masters: {
        Row: {
          prize_id: string
          prize_name: string
          prize_name_kana: string | null
          aliases: string | null
          short_name: string | null
          jan_code: string | null
          original_cost: number | null
          category: string | null
          size: string | null
          supplier_id: string | null
          supplier_name: string | null
          default_case_quantity: number | null
          status: 'active' | 'inactive'
          notes: string | null
          image_url: string | null
          organization_id: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          prize_id?: string
          prize_name: string
          prize_name_kana?: string | null
          aliases?: string | null
          short_name?: string | null
          jan_code?: string | null
          original_cost?: number | null
          category?: string | null
          size?: string | null
          supplier_id?: string | null
          supplier_name?: string | null
          default_case_quantity?: number | null
          status?: 'active' | 'inactive'
          notes?: string | null
          image_url?: string | null
          organization_id: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          prize_id?: string
          prize_name?: string
          prize_name_kana?: string | null
          aliases?: string | null
          short_name?: string | null
          jan_code?: string | null
          original_cost?: number | null
          category?: string | null
          size?: string | null
          supplier_id?: string | null
          supplier_name?: string | null
          default_case_quantity?: number | null
          status?: 'active' | 'inactive'
          notes?: string | null
          image_url?: string | null
          organization_id?: string
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      stores: {
        Row: {
          store_code: string
          store_name: string
          store_name_official: string | null
          locality: string | null
          locality_kana: string | null
          is_active: boolean
          is_collection_day: boolean
          organization_id: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          store_code: string
          store_name: string
          store_name_official?: string | null
          locality?: string | null
          locality_kana?: string | null
          is_active?: boolean
          is_collection_day?: boolean
          organization_id: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          store_code?: string
          store_name?: string
          store_name_official?: string | null
          locality?: string | null
          locality_kana?: string | null
          is_active?: boolean
          is_collection_day?: boolean
          organization_id?: string
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_latest_readings_per_booth: {
        Args: { p_booth_codes: string[] }
        Returns: Database['public']['Tables']['meter_readings']['Row'][]
      }
      get_last_readings_by_store: {
        Args: { p_store_code: string }
        Returns: {
          full_booth_code: string | null
          read_time: string | null
          in_meter: number | null
          out_meter: number | null
          prize_name: string | null
          patrol_date: string | null
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (Database['public']['Tables'] & Database['public']['Views'])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions['schema']]['Tables'] &
        Database[PublicTableNameOrOptions['schema']]['Views'])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions['schema']]['Tables'] &
      Database[PublicTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (Database['public']['Tables'] &
        Database['public']['Views'])
    ? (Database['public']['Tables'] &
        Database['public']['Views'])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof Database['public']['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof Database['public']['Tables']
    ? Database['public']['Tables'][PublicTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof Database['public']['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof Database['public']['Tables']
    ? Database['public']['Tables'][PublicTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof Database['public']['Enums']
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions['schema']]['Enums'][EnumName]
  : PublicEnumNameOrOptions extends keyof Database['public']['Enums']
    ? Database['public']['Enums'][PublicEnumNameOrOptions]
    : never
