-- SPEC-INF-MAIL-IMPORT-01 (D-086): inf-mail-import Edge Function の run ログ (sgp_import_logs 型)。
-- 本番適用は chat Claude。CC は本番 DDL 禁止 = 本ファイルは repo 記録用。Edge Function 側は inf_import_logs への
-- insert を best-effort (try/catch) にしてあるため、未適用でも取込本体は動作する。
CREATE TABLE IF NOT EXISTS inf_import_logs (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_at            timestamptz DEFAULT now(),
  records_fetched   integer DEFAULT 0,
  records_inserted  integer DEFAULT 0,
  records_updated   integer DEFAULT 0,
  records_skipped   integer DEFAULT 0,
  skipped_msg_ids   text[]  DEFAULT '{}',  -- 請書xlsx添付でスキップした msgId (announcements に残らないため別記録)
  errors            jsonb   DEFAULT '[]'::jsonb,
  duration_ms       integer
);
